### ISSUE TITLE
Run Command as a Login-Shell (MAC-Terminal > SSH)

### ISSUE THREAD

**Issue by ChristianSedlmair** [rvm/ubuntu_rvm#11]
Hello,
I'm working on a MAC and accessing the ubuntu by Terminal > SSH.
How can i activate "Run Command as a Login-Shell", like described in this Guide?
Best Regards,
Christian

**Comment by raelgc** [comment]
Hi @ChristianSedlmair.

This repository is for the Ubuntu package for RVM. Are you sure you installed using this Ubuntu package?

Anyway,  go to your terminal emulator preferences and enable login shell (i.e., make it run `/bin/bash --login`). Make sure to fully close terminal and open it fresh after changing the setting.

**Comment by ChristianSedlmair** [comment]
thanks, raelgc!
