### ISSUE TITLE
Installation on Ubuntu 17.10 fails

### ISSUE THREAD

**Issue by oslyak** [rvm/ubuntu_rvm#13]
Err:12 http://ppa.launchpad.net/rael-gc/rvm/ubuntu artful Release                                                                                            
  404  Not Found

**Comment by bibinvenugopal** [comment]
Even I have faced the same issue
When running

`sudo  apt-get update`

**http://ppa.launchpad.net/rael-gc/rvm/ubuntu artful Release                                                              
  404  Not Found
E: The repository 'http://ppa.launchpad.net/rael-gc/rvm/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.**

**Comment by gdledsan** [comment]
Work around : Change the distribution to zesty.

**Comment by pkuczynski** [comment]
@raelgc can you maybe have a look?

**Comment by guyellis** [comment]
@gdledsan (slightly off topic) my Google Foo didn't turn up any hints on how to change from Artful (17.10) to Zesty (17.04) - do you have any notes on doing this to solve this in the short-term?

**Comment by gdledsan** [comment]
@guyellis there are two ways:
1) Open Software & updates, go to other sources, find the repo and select it, hit edit and change the distribution from artful to zesty

2) open up the terminal and send
`sudo nano /etc/apt/sources.list.d/rael-gc-ubuntu-rvm-artful.list`
you will see a line like>
`deb http://ppa.launchpad.net/rael-gc/rvm/ubuntu artful main`
change it to 
`deb http://ppa.launchpad.net/rael-gc/rvm/ubuntu zesty main`
Save the file CTRL

**Comment by raelgc** [comment]
Package published in Artful. Sorry guys for the inconvenience.

**Comment by amritk** [comment]
I ran into the same issue and tried @gdledsan's fix but it doesn't work, am I missing something?

**Comment by gdledsan** [comment]
hey @amritk the release file is now added to the artful repo, so this issue should not happen. What error are you seeing?

**Comment by amritk** [comment]
@gdledsan It was a different ppa causing the issue. I used the fix from 
https://stackoverflow.com/a/23650993/1624255
and it now works.
