### ISSUE TITLE
No command 'rvm' found after installation

### ISSUE THREAD

**Issue by gswartz777** [rvm/ubuntu_rvm#16]
I'm on KDE, went through the steps outlined to install rvm but when I try to run any rvm commands (after rebooting) I get the error

No command 'rvm' found, but there are 26 similar ones
rvm: command not found

Any idea what I can check?

**Comment by gswartz777** [comment]
I thought this would work since KDE is on ubuntu but then I tried this command and it all works now.

\curl -sSL https://get.rvm.io | bash -s stable

**Comment by raelgc** [comment]
Hi @gswartz777.

This repo is to report errors related to the Ubuntu dedicated RVM package.
