### ISSUE TITLE
Ubuntu 18.04 support

### ISSUE THREAD

**Issue by Rumbles** [rvm/ubuntu_rvm#17]
I know it's only currently in Beta, but I was wondering if you plan on adding support for 18.04? I tried adding the PPA to my 18.04 beta machine and it complained there was no release file for bionic beaver.

Thanks

**Comment by lpaulmp** [comment]
@Rumbles For sure man, feel free to open a PR with the support.

**Comment by raelgc** [comment]
@Rumbles I just published the package for 18.04 on Launchpad. Let me know if it works.

**Comment by maxence33** [comment]
Hi. I tried to install RVM today on 18.04 and got error 

"The following packages have unmet dependencies:
 rvm : Depends: libreadline6 but it is not installable
E: Unable to correct problems, you have held broken packages."

**Comment by maxence33** [comment]
Ok this tutorial seems to work : https://gorails.com/setup/ubuntu/18.04
Think I followed the RVM install tutorial first place (Not sure why it then failed ...)
