### ISSUE TITLE
migrate from installation with curl

### ISSUE THREAD

**Issue by knzudgt** [rvm/ubuntu_rvm#18]
I installed rvm using the curl command, as suggested by the rvm website.
I wonder if is it possible to safely remove rvm and install the Ubuntu package, preserving rubies, gemsets and configuration files.

**Comment by raelgc** [comment]
Hi @knzudgt!

Yes: usually a `rvm implode` and logout should be enough.

But just take a look on the steps described in [StackOverflow](https://stackoverflow.com/a/3558763/1604312) to make sure you removed all.

**Comment by raelgc** [comment]
Let me know if this is still an issue.
