### ISSUE TITLE
libreadline6 issues on 18.04

### ISSUE THREAD

**Issue by fgblomqvist** [rvm/ubuntu_rvm#19]
When trying to install rvm from the official rvm ppa on Ubuntu 18.04 I get the following error:
```
The following packages have unmet dependencies:
 rvm : Depends: libreadline6 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
I tried manually installing libreadline6-dev, which worked fine, but I still get this error.

**Comment by raelgc** [comment]
Hi @fgblomqvist and thanks for reporting this issue. I'll fix in the next hours and publish the new version.

**Comment by raelgc** [comment]
@fgblomqvist I just published the package in the PPA. Can you run a `sudo apt update && sudo apt dist-upgrade` and tell me if it works fine?

**Comment by fgblomqvist** [comment]
Ran those commands but still the same error :/

**Comment by raelgc** [comment]
@fgblomqvist Can you, please, try again?

**Comment by fgblomqvist** [comment]
Now it worked, thanks!

**Comment by raelgc** [comment]
Yw! Thank you for reporting and testing!
