### ISSUE TITLE
The apt way

### ISSUE THREAD

**Issue by vmvwebworks** [rvm/ubuntu_rvm#26]
I suggest to still with the common way rather than the apt way for ubuntu, missing ruby versions and issues while installing them.

**Comment by raelgc** [comment]
@vmvwebworks This official rvm .deb package install the same stable version then rvm site. So it offers the same available rubies. If you want new, you can call `rvm get master` in the same way.

The issue found in the package version are the same stable version (ssl, folder permissions, etc).

The advantages of the package over an installer are basically the same the when comparing with any other installer:

- the package has automatic updates
- has a clean uninstall
- install in proper folders respecting Ubuntu guides
- automatically adds all sudoers into `rvm` group
- runs a mixed install allowing global rubies with local gemsets.

Anyway, if you want to point which exact issues you're facing, feel free to open new issues.
