### ISSUE TITLE
 '~rael-gc' user or team does not exist.

### ISSUE THREAD

**Issue by maysam** [rvm/ubuntu_rvm#27]
when I run

`sudo apt-add-repository -y ppa:rael-gc/rvm`

it says

`Cannot add PPA: 'ppa:~rael-gc/ubuntu/rvm'.`
`ERROR: '~rael-gc' user or team does not exist.`

**Comment by raelgc** [comment]
Hi @maysam. Can you just try again? Sometimes the Launchpad servers will go out for some minutes.

You can check this PPA exists in Launchpad: https://launchpad.net/~rael-gc/+archive/ubuntu/rvm

**Comment by maysam** [comment]
@raelgc I tried a few times, same problem

**Comment by raelgc** [comment]
Are you under a proxy?

**Comment by maysam** [comment]
it worked on another machine, not sure what was wrong on my machine, that's for your time and your help

**Comment by raelgc** [comment]
@maysam Sounds like a machine under a proxy. Maybe you want to take a look on instructions to [add-apt-repository to work through a proxy](https://askubuntu.com/questions/53146/how-do-i-get-add-apt-repository-to-work-through-a-proxy).

**Comment by Thornybastard** [comment]
I'm having the same problem as this guy and I know I'm not behind a proxy. I'm using my home internet and no vpn or anything.

**Comment by simonlennon-advanced** [comment]
Same issue too no proxy

**Comment by gdandersson** [comment]
Same problem, in a virtual machine with no proxy. On ARM64, if that matters.
