### ISSUE TITLE
no rvm group created

### ISSUE THREAD

**Issue by maysam** [rvm/ubuntu_rvm#28]
I noticed that the installer didn't create an rvm group , is that a problem?

**Comment by raelgc** [comment]
What is the output of `groups` command?

**Comment by raelgc** [comment]
Make sure you've restarted your machine.

**Comment by raelgc** [comment]
And please, output of `cut -d: -f1 /etc/group | sort`

**Comment by maysam** [comment]
actually rvm is in this list

but when I run 'groups' command it doesnt list rvm

nevertheless
when I run 
`rvm install 2.3.7`

i get an error

`Warning: Failed to create the file ruby-2.3.7.tar.bz2.part: Permission denied`


so I need to do
`rvmsudo rvm install 2.3.7`

is this normal?

**Comment by raelgc** [comment]
Had you restarted your machine?

**Comment by raelgc** [comment]
And `rvmsudo` is not required to install a ruby or create gemset.

**Comment by maysam** [comment]
you are correct again, I had to restart
