### ISSUE TITLE
Opening a new window/tab in a directory .ruby-version & .ruby-gemset specs are ignored

### ISSUE THREAD

**Issue by iridakos** [rvm/ubuntu_rvm#29]
## Description

When opening
- a new terminal window
  - from inside a **terminal** using the menu (or shortcuts) or
  - by choosing `Open in terminal` on a directory in **nautilus** or
- a new terminal tab

and the directory of the new window/tab has `.ruby-version` and `.ruby-gemset` files, rvm ignores them.

### Terminal
1. `cd` to a directory with `.ruby-version` and `.ruby-gemset` configuration files
2. execute `rvm list` and `rvm gemset list` to confirm that the options are respected
3. open a new tab or window (either by the menu or with shortcuts (`ctrl+shift+n` or `ctrl+shift+t`)
4. execute `rvm list` and `rvm gemset list`
  => **both ruby version and gemset are set to the defaults**
5. if you `cd .` then rvm will set them correctly

### Nautilus
1. navigate to a directory that has `.ruby-version` and `.ruby-gemset` files
2. right click on the directory and choose `Open in terminal`
3. in the terminal that has opened, execute `rvm list` and `rvm gemset list` 
  => **both ruby version and gemset are set to the defaults**
4. if you `cd .` then rvm will set them correctly

**Comment by raelgc** [comment]
Hi @iridakos,

If you're using gnome terminal at Ubuntu 14.04, this is not a `rvm` problem, it's a known bug of gnome terminal.

If you're not using gnome terminal in Ubuntu 14.04, please make sure that, after a system restart, you've marked your terminal to execute a login shell like stated in these instructions: https://github.com/rvm/ubuntu_rvm#2-change-your-terminal-window

**Comment by iridakos** [comment]
Hi @raelgc and thank you for the response.

I am on Ubuntu 18.04 LTS and I am using the gnome terminal.
The profile is also set to execute a login shell.

Let me know if additional information would help.

Thank you for your time.

**Comment by raelgc** [comment]
Np! Thanks for reporting this.

Can you, please, open this bug in the https://github.com/rvm/rvm/ repo? This repo will request you several details, but please, remember to mention that your terminal is already running as login shell.

**Comment by iridakos** [comment]
I will! Thank ;)
