### ISSUE TITLE
vagrant user is not added to rvm group

### ISSUE THREAD

**Issue by vvavrychuk** [rvm/ubuntu_rvm#31]
In `ubuntu/xenial64` vagrant machine vagrant user (default one) is given with sudoers permissions via `/etc/sudoers.d/vagrant` and not by adding it to the `sudo` group.

Therefore ubuntu_rvm fails to add it to the `rvm` group.

From one side a good way for ubuntu_rvm to determine list of users with sudo permissions would be sudo command itself. Close match is something like `sudo -l -U user-name` or `sudo -ll -U user-name` but its interface seems not scriptable.

**Comment by raelgc** [comment]
@vvavrychuk Do you mind to open a PR with this? 

The script responsible for adding sudoers is the `postinst` in the debian package source: https://github.com/rvm/ubuntu_rvm/blob/master/debian/postinst

**Comment by vvavrychuk** [comment]
@raelgc I have reported lack of scriptable version of 'sudo --list' here https://bugzilla.sudo.ws/show_bug.cgi?id=862.

**Comment by raelgc** [comment]
I just found today in the docker setup commands (I reminded of this issue) that we can run the following command to activate the changes to groups:

    newgrp rvm
