### ISSUE TITLE
Failed to fetch http://ppa.launchpad.net/rael-gc/rvm/ubuntu/dists/eoan/main/binary-amd64/Packages

### ISSUE THREAD

**Issue by Blusten23** [rvm/ubuntu_rvm#34]
I am trying to install rvm in docker:
FROM jenkins/jenkins:lts
...
RUN sudo apt-get install -y software-properties-common
RUN sudo apt-add-repository -y ppa:rael-gc/rvm
RUN sudo apt-get update && sudo apt dist-upgrade
RUN sudo apt-get install -y rvm --allow-unauthenticated

I get this error:
E: Failed to fetch http://ppa.launchpad.net/rael-gc/rvm/ubuntu/dists/eoan/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c sudo apt-get update && sudo apt dist-upgrade' returned a non-zero code: 100

**Comment by raelgc** [comment]
Hi @Blusten23. Which Ubuntu version is `eoan`?

**Comment by raelgc** [comment]
In Launchpad I'm tied to the official Ubuntu versions (I cannot user other versions to build packages). If you really want to use this PPA, you'll need to find the related Ubuntu version that matches `eoan` and tweak your apt sources manually.

**Comment by raelgc** [comment]
Just checked now that this is the name of the announced future version of Ubuntu announced few days ago, `Eoan`.

Of course, I still didn't test the package on that version, as it started to receive daily builds few hours ago.

I'll re-open, as probably in 4 months I'll need to publish on it, after the official release.

Wondering why you're trying to use that too alpha stage release...

**Comment by Blusten23** [comment]
@raelgc what do you mean by "alpha stage release"?
I am using jenkins offficial docker image and then install some stuff like docker, k8s and then rvm and ruby, there is no specific alpha release, or am i not noticing it?

**Comment by raelgc** [comment]
@Blusten23 Ubuntu `eoan` started to get daily builds only YESTERDAY. There is not even alpha, beta or release candidate. It'll be released only in October. Something is wrong in your setup.

**Comment by SebCargo** [comment]
I'm having the same problem. I'm using a VM with Debian Stretch. And for some reasons is setting the PPA with eoan as release.

to fix the problem I installed the ppa with the syntax 

> add-apt-repository 'deb http://ppa.launchpad.net/rael-gc/rvm/ubuntu disco main'

And 

> apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7BE3E5681146FD4F1A40EDA28094BB14F4E3FBBE

**Comment by raelgc** [comment]
Just published for Eoan, which was released this week.
