### ISSUE TITLE
No /usr/share/rvm

### ISSUE THREAD

**Issue by wytcld** [rvm/ubuntu_rvm#35]
In fact, no "rvm" anywhere on the system. There is a /home/ubuntu/.rvm directory, but no "rvm." Yet the apt installation appeared to complete without error. This is with Ubuntu 18.04.

**Comment by raelgc** [comment]
`rvm` folder will be created, of course, during the package install. Please, add the error log that happened during the install.

**Comment by raelgc** [comment]
@wytcld Please, clarify one question: you installed using the dedicated PPA or you've installed using rvm.io? 

And, again, please, can you attach the error log that happened during the package install?

**Comment by raelgc** [comment]
@wytcld In case you're still facing this issue, please re-open.

**Comment by SuperSandro2000** [comment]
> @wytcld In case you're still facing this issue, please re-open.

FYI I saw this sentence a lot and it always confuses me cause I can't reopen the issue myself.

**Comment by raelgc** [comment]
If you don't have the permission to re-open, just leave a comment and we'll re-open the issue.

The reason: some users open a defect without enough information, even when requested. If no info is provided after some weeks, we'll close the defect (or re-open if more info is provided). Wide open source projects will have a lot of defects to be handled (usually by few volunteers), so we'll focus on the priorities and issues with the proper feedback.
