### ISSUE TITLE
Discrepencies between freshly installed 'rvm' instructions and the README directions

### ISSUE THREAD

**Issue by aegatlin** [rvm/ubuntu_rvm#36]
After installing rvm, there are instructions on how to proceed:

```
Installation of RVM in /usr/share/rvm/ is almost complete:

  * First you need to add all users that will be using rvm to 'rvm' group,
    and logout - login again, anyone using rvm will be operating with `umask u=rwx,g=rwx,o=rx`.

  * To start using RVM you need to run `source /etc/profile.d/rvm.sh`
    in all your open shell windows, in rare cases you need to reopen all shell windows.
  * Please do NOT forget to add your users to the rvm group.
     The installer no longer auto-adds root or users to the rvm group. Admins must do this.
     Also, please note that group memberships are ONLY evaluated at login time.
     This means that users must log out then back in before group membership takes effect!
Thanks for installing RVM 🙏
Please consider donating to our open collective to help us maintain RVM.

👉  Donate: https://opencollective.com/rvm/donate
```

These instructions differ, or at least go unmentioned, in the README directions in this repo. As a new user, this is confusing.

### Expected behaviour
I expect the rvm terminal instructions to at least be mentioned in the README instructions. Moreover, I would prefer that they are incorporated.

**Comment by raelgc** [comment]
Indeed, this is in my plate for some time. I'll update the instructions displayed in the terminal to be compatible with the README.

Just to make clear: the README instructions are updated. This package will add all sudoers to rvm group and automatically do all the setup. You just need, like stated in the README, restart.

**Comment by raelgc** [comment]
With the `1.29.10` release, I've removed the warning #3, but forgot about the #1...

**Comment by raelgc** [comment]
I changed the package behavior now to follow `rvm`: sudoers are no more automatically added. I added instructions to `README` to guide users.
