### ISSUE TITLE
Instructions on the Readme do not work

### ISSUE THREAD

**Issue by egee-irl** [rvm/ubuntu_rvm#42]
## Description

I followed the instructions word-for-word from the Readme and RVM is not in my path nor does it work at all.

## Steps to reproduce

 1. Follow the steps on the Readme
 2. Logout & Back in
 3. Open a terminal & type `man rvm`

## Expected behavior

Man pages for rvm should appear

## Actual behavior

No manual entry for rvm

## Environment info

```
DISTRIB_ID=elementary
DISTRIB_RELEASE=5.0
DISTRIB_CODENAME=juno
DISTRIB_DESCRIPTION="elementary OS 5.0 Juno"
```

ALSO, the readme states `you're now member of rvm group)` but the installer says that the installer no longer does this.

**Comment by raelgc** [comment]
Hi @egee-irl and thanks for reporting this issue.

What happens when you type `rvm --version`?

About the mismatching info on README and installer, yeap, it's ugly. Fortunately we already have #36 for that, which I'll address in the next release.

**Comment by egee-irl** [comment]
It says

`Command rvm not found, but there are 21 similar ones.`

**Comment by SuperSandro2000** [comment]
It probably added `juno` as a distribution which is not in the ppa. Try changing `/etc/apt/sources.list.d/*rvm*` to `disco` or something that is available.

**Comment by raelgc** [comment]
@egee-irl any lucky trying the solution pointed by @SuperSandro2000? In fact, you just added the PPA, but as you're using Elementary, `apt` has not matched your system version, so `rvm` package is not installed in your system.

**Comment by egee-irl** [comment]
elementaryOS is based on Ubuntu LTS which is currently `bionic`. And as such, the entry in the apt sources is correct. It shows:

`deb http://ppa.launchpad.net/rael-gc/rvm/ubuntu bionic main`

**Comment by raelgc** [comment]
What is the output of `sudo apt install rvm`?

**Comment by egee-irl** [comment]
![image](https://user-images.githubusercontent.com/6679968/71381560-da82b300-2588-11ea-8ec1-c515bdb50929.png)

**Comment by raelgc** [comment]
@egee-irl Thanks for the feedback!

Dummy question: had you restarted your system?

What happens if you run `source /etc/profile.d/rvm.sh` and then try call `rvm`?

**Comment by egee-irl** [comment]
The `rvm.sh` actually wasn't there, despite apt claiming rvm was installed. I reinstalled rvm and the script showed up. After I sourced it, running `which rvm` yielded `/usr/share/rvm/bin/rvm`

**Comment by egee-irl** [comment]
I'm going to close this issue because I think it was some sort of configuration related issue.

It's _possible_ that it could be related to elementaryOS but ultimately I did not find the root cause.

If this happens in the future for people, I recommend:

* Verify the rvm PPA is correctly installed
* Purge rvm with apt
* Reinstall rvm with apt
