### ISSUE TITLE
`Following files may not be writable, so sudo is needed` after upgrade to 1.29.10

### ISSUE THREAD

**Issue by ShockwaveNN** [rvm/ubuntu_rvm#45]
## Description

I just received update on my kubuntu 18.04 via apt-get from rvm 1.29.9-3 to 1.29.10-1 and now in every terminal I opened I receive this error:
```
Following files may not be writable, so sudo is needed:
  /home/user/.rvm/gems/ruby-2.6.5/environment
```
There is was no such error with 1.29.9-3

## Environment info

```
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```

**Comment by raelgc** [comment]
Hi @ShockwaveNN and thanks for reporting this issue.

Please, can you try run this command?

    rvmsudo rvm cleanup all

**Comment by ShockwaveNN** [comment]
@raelgc Yeah, thanks, seems this helped with my issue and error message is gone

Maybe this should be added in Readme that `In case in any error message please try to run `rvmsudo rvm cleanup all` before reporting issue`

**Comment by ShockwaveNN** [comment]
Oh, sorry this error gone on opening new terminal, but still present if I call any ruby program.
Except ruby itself
![image](https://user-images.githubusercontent.com/668524/77732778-a7800d80-7016-11ea-99df-22c8a6f447b5.png)

**Comment by raelgc** [comment]
@ShockwaveNN It was already added in the `README` file.

Which is the permission for this `environment` file?

**Comment by ShockwaveNN** [comment]
@raelgc Seems reboot of my PC fixed the problem

Now permissions is:
```
-rw-rw-r-- 1 root root 469 мар 26 17:32 /home/lobashov/.rvm/gems/ruby-2.6.5/environment
```
and seems everything is fine.

>It was already added in the README file. 

Yeah, it's in `3. Cannot upgrade to rvm master due Operation not permitted` paragraph. But I think there should be note that in all troubleshooting sessions this command should be performed, if I understand that right

**Comment by raelgc** [comment]
@ShockwaveNN I agree. I just improved the troubleshooting section item 3.

**Comment by ShockwaveNN** [comment]
@raelgc to be clear (First I was thinking that reboot is helped me, but actually not) this problem is still actual for me

**Comment by raelgc** [comment]
@ShockwaveNN Can you try change the owning of the `.rvm` content folder back to you?

    sudo chown -r lobashov:lobashov /home/lobashov/.rvm/

**Comment by ShockwaveNN** [comment]
@raelgc Yeah, seems this fixed my problem

Only you got a typo - `-R`, capitall letter like this:
```
sudo chown -R lobashov:lobashov /home/lobashov/.rvm/
```

Thank you, I'll close this issue
