### ISSUE TITLE
Changelog not retrievable from apt

### ISSUE THREAD

**Issue by danielpclark** [rvm/ubuntu_rvm#5]
From synaptic package manager: 

> This change is not coming from a source that supports changelogs.
>
> Failed to fetch the changelog for rvm
> URI was: http://ppa.launchpad.net/pool/main/r/rvm/rvm_1.29.1-1_all.changelog

**Comment by raelgc** [comment]
Synaptic is not able to get changelog for apps in PPAs:

> launchpad doesn't provide a normalized way to fetch the changelog for a PPA. Currently, the only way to retrieve the changelog url is to use the lp api and that won't be implemented into synaptic.

from https://bugs.launchpad.net/ubuntu/+source/synaptic/+bug/153966

Anyway, check the official [RVM changelog](https://github.com/rvm/rvm/blob/master/CHANGELOG.md).
