### ISSUE TITLE
Error running 'requirements_debian_update_system ruby-2.7.0',

### ISSUE THREAD

**Issue by george-carlin** [rvm/ubuntu_rvm#50]
## Description

I followed the README's instructions to install RVM on Ubuntu 20.04, including having restarted my machine, but I get the following error whenever I try to install a Ruby:

```
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/20.04/x86_64/ruby-2.7.0.tar.bz2
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating system - please wait
There has been an error while updating your system using `apt-get`.
It seems that there are some 404 Not Found errors for repositories listed in:

    /etc/apt/sources.list
    /etc/apt/sources.list.d/*.list

Make sure that all repositories are available from your system and verify your setup by running manually:

    sudo apt-get update

Make sure that it works correctly before proceeding with RVM.

If you are working from the GUI instead of the terminal, you might want to verify and fix broken
repositories using "Software & Updates" application.

Error running 'requirements_debian_update_system ruby-2.7.0',
please read /home/george/.rvm/log/1603454373_ruby-2.7.0/update_system.log
Requirements installation failed with status: 100.
```

The `log` file mentioned in that error message contains the followign:

<details>
<summary>Click to expand</summary>
<pre>
+requirements_debian_update_system:2> __rvm_try_sudo apt-get --quiet --yes update
+__rvm_try_sudo:2> typeset -a command_to_run
+__rvm_try_sudo:3> typeset sudo_path sbin_path missing_paths
+__rvm_try_sudo:4> command_to_run=( apt-get --quiet --yes update ) 
+__rvm_try_sudo:5> ((  UID == 0  ))
+__rvm_try_sudo:6> case 4 (0)
+__rvm_try_sudo:6> case 4 (1)
+__rvm_try_sudo:6> case 4 (2)
+__rvm_try_sudo:6> case 4 (*)
+__rvm_try_sudo:21> is_a_function __rvm_sudo
+is_a_function:2> typeset -f __rvm_sudo
+__rvm_try_sudo:23> missing_paths='' 
+__rvm_try_sudo:24> sbin_path=/sbin
+__rvm_try_sudo:26> [[ -d /sbin ]]
+__rvm_try_sudo:26> [[ :/home/george/.nvm/versions/node/v15.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/share/rvm/bin:/usr/local/go/bin:/home/george/Android/Sdk/emulator:/home/george/Android/Sdk/tools:/home/george/Android/Sdk/tools/bin:/home/george/Android/Sdk/platform-tools: != *:/sbin:* ]]
+__rvm_try_sudo:24> sbin_path=/usr/sbin
+__rvm_try_sudo:26> [[ -d /usr/sbin ]]
+__rvm_try_sudo:26> [[ :/home/george/.nvm/versions/node/v15.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/share/rvm/bin:/usr/local/go/bin:/home/george/Android/Sdk/emulator:/home/george/Android/Sdk/tools:/home/george/Android/Sdk/tools/bin:/home/george/Android/Sdk/platform-tools: != *:/usr/sbin:* ]]
+__rvm_try_sudo:24> sbin_path=/usr/local/sbin
+__rvm_try_sudo:26> [[ -d /usr/local/sbin ]]
+__rvm_try_sudo:26> [[ :/home/george/.nvm/versions/node/v15.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/share/rvm/bin:/usr/local/go/bin:/home/george/Android/Sdk/emulator:/home/george/Android/Sdk/tools:/home/george/Android/Sdk/tools/bin:/home/george/Android/Sdk/platform-tools: != *:/usr/local/sbin:* ]]
+__rvm_try_sudo:30> [[ -n '' ]]
+__rvm_try_sudo:33> command_to_run=( __rvm_sudo -p '%p password required for '\''apt-get --quiet --yes update'\'': ' apt-get --quiet --yes update ) 
+__rvm_try_sudo:40> __rvm_sudo -p '%p password required for '\''apt-get --quiet --yes update'\'': ' apt-get --quiet --yes update
+__rvm_sudo:2> sudo -p '%p password required for '\''apt-get --quiet --yes update'\'': ' apt-get --quiet --yes update
Hit:1 http://ppa.launchpad.net/rael-gc/rvm/ubuntu focal InRelease
Hit:2 http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_20.04  InRelease
Ign:3 http://ppa.launchpad.net/teatime/ppa/ubuntu focal InRelease
Hit:4 http://gb.archive.ubuntu.com/ubuntu focal InRelease
Get:5 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Ign:6 http://binaries.erlang-solutions.com/debian focal InRelease
Get:7 http://gb.archive.ubuntu.com/ubuntu focal-updates InRelease [111 kB]
Hit:8 http://binaries.erlang-solutions.com/debian focal Release
Err:9 http://ppa.launchpad.net/teatime/ppa/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]
Get:10 https://cli.github.com/packages focal InRelease [3,024 B]
Get:11 http://gb.archive.ubuntu.com/ubuntu focal-backports InRelease [98.3 kB]
Get:12 https://repo.skype.com/deb stable InRelease [4,502 B]
Get:13 https://download.docker.com/linux/ubuntu bionic InRelease [64.4 kB]
Get:14 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Get:15 http://dl.google.com/linux/chrome/deb stable InRelease [1,811 B]
Err:5 https://dl.yarnpkg.com/debian stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
Err:10 https://cli.github.com/packages focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C99B11DEB97541F0
Err:12 https://repo.skype.com/deb stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1F3045A5DF7587C3
Err:15 http://dl.google.com/linux/chrome/deb stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 78BD65473CB3BD13
Reading package lists...
E: The repository 'http://ppa.launchpad.net/teatime/ppa/ubuntu focal Release' does not have a Release file.
W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
W: GPG error: https://cli.github.com/packages focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C99B11DEB97541F0
E: The repository 'https://cli.github.com/packages focal InRelease' is not signed.
W: GPG error: https://repo.skype.com/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1F3045A5DF7587C3
E: The repository 'https://repo.skype.com/deb stable InRelease' is not signed.
W: GPG error: http://dl.google.com/linux/chrome/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 78BD65473CB3BD13
E: The repository 'http://dl.google.com/linux/chrome/deb stable InRelease' is not signed.
+__rvm_try_sudo:40> return 100
+requirements_debian_update_system:4> typeset '__ret=100'
+requirements_debian_update_system:5> case 100 (100)
+requirements_debian_update_system:7> rvm_error $'There has been an error while updating your system using `apt-get`.\nIt seems that there are some 404 Not Found errors for repositories listed in:\n\n    /etc/apt/sources.list\n    /etc/apt/sources.list.d/*.list\n\nMake sure that all repositories are available from your system and verify your setup by running manually:\n\n    sudo apt-get update\n\nMake sure that it works correctly before proceeding with RVM.\n\nIf you are working from the GUI instead of the terminal, you might want to verify and fix broken\nrepositories using "Software & Updates" application.\n'
+rvm_error:2> rvm_pretty_print stderr
+rvm_pretty_print:2> case auto (0|no)
+rvm_pretty_print:2> case auto (1|auto)
+rvm_pretty_print:8> case xterm-256color (dumb|unknown)
+rvm_pretty_print:12> case stderr (stdout)
+rvm_pretty_print:12> case stderr (stderr)
+rvm_pretty_print:14> [[ -t 2 ]]
+rvm_pretty_print:14> return 1
+rvm_error:4> printf %b $'There has been an error while updating your system using `apt-get`.\nIt seems that there are some 404 Not Found errors for repositories listed in:\n\n    /etc/apt/sources.list\n    /etc/apt/sources.list.d/*.list\n\nMake sure that all repositories are available from your system and verify your setup by running manually:\n\n    sudo apt-get update\n\nMake sure that it works correctly before proceeding with RVM.\n\nIf you are working from the GUI instead of the terminal, you might want to verify and fix broken\nrepositories using "Software & Updates" application.\n\\n'
+requirements_debian_update_system:24> return 100
</pre>
</details>

I've tried running `sudo apt-get update` like the error message suggests and it seems to run fine, but I still get the same error message.

What am I doing wrong?

**Comment by georgemillo** [comment]
(Should add that running `rvm fix-permissions` doesn't make a difference either.)

**Comment by raelgc** [comment]
Whats the output of `sudo apt update`?

**Comment by georgemillo** [comment]
```
$ sudo apt update
[sudo] password for george: 
Hit:1 http://gb.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://gb.archive.ubuntu.com/ubuntu focal-updates InRelease [111 kB]                                                                                                                                        
Get:3 http://gb.archive.ubuntu.com/ubuntu focal-backports InRelease [98.3 kB]                                                                                                                                     
Get:4 https://repo.skype.com/deb stable InRelease [4,502 B]                                                                                                                                                       
Get:5 http://dl.google.com/linux/chrome/deb stable InRelease [1,811 B]                                                                                                                                            
Get:6 https://download.docker.com/linux/ubuntu bionic InRelease [64.4 kB]                                                                                                                                         
Hit:7 http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_20.04  InRelease                                                                                                                    
Get:8 https://cli.github.com/packages focal InRelease [3,024 B]                                                                                                                                                   
Get:9 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]                                                                                                       
Ign:10 http://binaries.erlang-solutions.com/debian focal InRelease                                                                
Get:11 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]                     
Hit:12 http://binaries.erlang-solutions.com/debian focal Release                                          
Get:13 http://gb.archive.ubuntu.com/ubuntu focal-updates/main amd64 DEP-11 Metadata [229 kB]              
Get:14 http://gb.archive.ubuntu.com/ubuntu focal-updates/universe amd64 DEP-11 Metadata [202 kB]                                                     
Get:15 http://gb.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [2,468 B]                                                                    
Get:16 http://gb.archive.ubuntu.com/ubuntu focal-backports/universe amd64 DEP-11 Metadata [1,768 B]                                                  
Err:4 https://repo.skype.com/deb stable InRelease                                                                                                                        
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1F3045A5DF7587C3
Err:5 http://dl.google.com/linux/chrome/deb stable InRelease                                                                   
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 78BD65473CB3BD13
Err:8 https://cli.github.com/packages focal InRelease        
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C99B11DEB97541F0
Err:9 https://dl.yarnpkg.com/debian stable InRelease         
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
Get:18 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [24.2 kB]
Get:19 http://security.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [55.7 kB]       
Err:20 http://ppa.launchpad.net/rael-gc/rvm/ubuntu focal InRelease                                                                                                                                                
  Cannot initiate the connection to ppa.launchpad.net:80 (2001:67c:1560:8008::15). - connect (101: Network is unreachable) Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
Err:21 http://ppa.launchpad.net/teatime/ppa/ubuntu focal InRelease
  Cannot initiate the connection to ppa.launchpad.net:80 (2001:67c:1560:8008::15). - connect (101: Network is unreachable)
Reading package lists... Done
W: GPG error: https://repo.skype.com/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1F3045A5DF7587C3
E: The repository 'https://repo.skype.com/deb stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://dl.google.com/linux/chrome/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 78BD65473CB3BD13
E: The repository 'http://dl.google.com/linux/chrome/deb stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://cli.github.com/packages focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C99B11DEB97541F0
E: The repository 'https://cli.github.com/packages focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details
```

**Comment by raelgc** [comment]
Interesting, for some reason your `apt` is not reading any Canonical Launchpad PPA (which includes the `rvm` one and others). Are you under a company/university proxy, something like that?

**Comment by georgemillo** [comment]
Nope, I'm at home using my regular Internet connection. No proxies/VPNs/firewalls that I'm aware of.

I can visit ppa.launchpad.com in my browser, so I don't think I'm blocked from accessing this domain.

**Comment by raelgc** [comment]
Ok. You'll need to fix your `apt` not reaching the PPAs problem. If not, the alternative would be remove all PPAs from your repositories list, then try to install regular `rvm` instead of the packaged one.

**Comment by yassine-safraoui** [comment]
I faced the same issue, a restart solved the problem for me, actually it's mentionned in the installation guide that it's needed.
