### ISSUE TITLE
Please update the PPA for Ubuntu Groovy Gorilla

### ISSUE THREAD

**Issue by darthmooguy** [rvm/ubuntu_rvm#51]
## Description

Hello, 

Could you please update the PPA for Ubuntu Groovy Gorilla? The last available version in the PPA is for Ubuntu Focal.

Thanks a lot!

## Environment info

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Ubuntu 20.10"
```

**Comment by raelgc** [comment]
Ops, sorry for that. They're in place now. Thanks for raising this issue!
