### ISSUE TITLE
1.29.12 release?

### ISSUE THREAD

**Issue by ShockwaveNN** [rvm/ubuntu_rvm#54]
rvm 1.29.12 [released 17 days ago](https://github.com/rvm/rvm/releases/tag/1.29.12)

Is there is a planning update to update ppa as well?

**Comment by pkuczynski** [comment]
@raelgc ?

**Comment by raelgc** [comment]
I'm working on it right now. I delayed because my expectation was that I was able to solve the binary problems related to the difference between Ubuntu 20.04 and 20.04.1.

**Comment by raelgc** [comment]
In place now for all supported Ubuntu versions in Launchpad.

**Comment by ShockwaveNN** [comment]
Can confirm, rvm 1.29.12 is installed on Ubuntu 20.04

**Comment by raelgc** [comment]
@ShockwaveNN Thanks for the feedback and thanks for opening this issue. And sorry for the delay.

**Comment by ShockwaveNN** [comment]
@raelgc No worries :+1:
