### ISSUE TITLE
Please update the PPA for Ubuntu Hirsute Hippo

### ISSUE THREAD

**Issue by gicatalan** [rvm/ubuntu_rvm#56]
## Description

Hello,

could you please update the PPA for Ubuntu Hirsute Hippo? The last available version in the PPA is for Ubuntu Groovy.

Thanks a lot!

## Environment info

```shell
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
```

P.S. Déjà vu?

**Comment by raelgc** [comment]
Hi @gicatalan, thanks for the friendly reminder!

I just published the packages!
