### ISSUE TITLE
Please update the PPA for Ubuntu Impish Indri

### ISSUE THREAD

**Issue by franciscomasi** [rvm/ubuntu_rvm#62]
# Description

Hello,

could you please update the PPA for Ubuntu Impish Indri? The last available version in the PPA is for Ubuntu Hirsute.

Thanks a lot!

Environment info
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"
```

**Comment by raelgc** [comment]
Hi @franciscomasi, thanks for raising this. Files are in place now. Sorry for the inconvenience.
