### ISSUE TITLE
a lower gid for rvm would be more appropiate

### ISSUE THREAD

**Issue by smartyjones** [rvm/ubuntu_rvm#64]
## Description

When installing the package on ubuntu, it creates group rvm with the next available groupid in the higher of id's. Mostly it will be 1001. I think it would be more appropiate to use the lower id's and create a group with parameter -r or --system for rvm.

## Steps to reproduce

 1. Just install rvm package as described in the README.
 2. cat /etc/group | grep rvm #and check the gid
 
## Expected behavior

 1. Just install rvm package as described in the README.
 2. cat /etc/group | grep rvm #gid is should be in the lower range

## Actual behavior

See steps to repoduce

## Environment info

This was done on a WSL2 ubuntu20.04.

**Comment by raelgc** [comment]
Hi @smartyjones, thanks for reporthing issue. I'm glad to know this works on WSL2.

I'm afraid that I cannot help you with this as this repo is only for the Ubuntu package itself and the group creation is performed by `rvm` installer script.

I.e., probably you should raise this issue on [rvm/rvm](https://github.com/rvm/rvm) repo.
