### ISSUE TITLE
Incorrectly ordered/formatted changes to user .profile/.bash* files

### ISSUE THREAD

**Issue by derrelldurrett** [rvm/ubuntu_rvm#7]
After following the instructions, I get no `ruby` available at the command line (nor `irb` nor any other tools other than `rvm`).

I note that my `.bashrc` and similar files do not reflect the different paths for `rvm`, and so am wondering what other changes I should be aware of needing to make. For example, where should `PATH` be modified to point to `/usr/share/rvm/rubies/ruby-2.4.0/bin`?

**Comment by raelgc** [comment]
Aside logout and login, you need to make sure your terminal is running as a login shell.

**Comment by raelgc** [comment]
Oh, after install rvm, you need to [follow the instructions to install a ruby](https://github.com/rvm/rvm#installing-ruby).
