### ISSUE TITLE
Absent `~/.rvm` on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by OleStan** [rvm/ubuntu_rvm#71]
## Description

I have installed rvm 1.29.12 on Ubuntu 22.04 LTS, and realize that there is no `~/.rvm`. But I can call rvm in terminal and download ruby versions

## Steps to reproduce

 1. Install rvm
```
sudo apt-add-repository -y ppa:rael-gc/rvm
sudo apt-get update
sudo apt-get install rvm
sudo usermod -a -G rvm $USER
echo 'source "/etc/profile.d/rvm.sh"' >> ~/.bashrc
```
 2. Install minimal Ruby for Ubuntu 22.04 
```
rvm install 3.1.0
```
 3. Check user directory 
`cd ~/.rvm`
4. Get output that `-bash: cd: /home/use/.rvm: No such file or directory`

## Expected behavior

_~/.rvm_ present and I can run capistrano task

## Actual behavior

```
~$ cd ~/.rvm
-bash: cd: /home/deployer/.rvm: No such file or directory
```

## Environment info

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
rvm 1.29.12 (manual) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]

**Comment by jpriollaud** [comment]
@OleStan This flavor of RVM uses mixed-mode and puts the rvm binaries in /usr/share/rvm instead.
See the very top of the Readme https://github.com/rvm/ubuntu_rvm#rvm-package-for-ubuntu

Some have apparently decided to symlink between ~/.rvm and /usr/share but it's probably not worth it.  Just update your paths everywhere.
