### ISSUE TITLE
Why not just tell users to run `su $USER`?

### ISSUE THREAD

**Issue by ctrlcctrlv** [rvm/ubuntu_rvm#73]
Just curious! Instead of the reboot or log in/log out step.

**Comment by raelgc** [comment]
Because that way you'll run commands as super user and `rvm` doesn't require that. And when you've joined a new group, a logout is required. There are workarounds for that, anyway.

**Comment by ctrlcctrlv** [comment]
Worked for me. Also you're wrong about what `su` does. The password `su` takes is the current account password, it only is the root password if no login name specified.

**Comment by raelgc** [comment]
Yes, you're right, it'll basically works like a new login until you close the terminal. I never tested if it'll really load user new groups.

**Comment by ctrlcctrlv** [comment]
Yup it does :-) that's why I suggested it. It's OK, it's a weird POSIX internal thing. `sudo` = `set user and do` not `superuser-do`!
