### ISSUE TITLE
Unable to install RVM in Ubuntu 22.04 Docker

### ISSUE THREAD

**Issue by jgfoster** [rvm/ubuntu_rvm#76]
## Description

The instructions seem to be incomplete.

## Steps to reproduce

On an Ubuntu 22.04 Docker image, I installed `software-properties-common` and successfully installed rvm (`rvm is already the newest version (1.29.12-1)`). When I try the next step, `sudo usermod -a -G rvm $USER`, I get the error that `usermod: group 'rvm' does not exist`. If I `cat /etc/profile.d/rvm.sh` it says that the file is not found.

## Expected behavior

Group and file exist.

## Actual behavior

```
FROM ubuntu:22.04
RUN apt-get update && apt-get install -y software-properties-common
RUN apt-add-repository -y ppa:rael-gc/rvm
RUN apt-get update && apt-get install -y rvm
RUN usermod -a -G rvm $USER
RUN source "/etc/profile.d/rvm.sh"
RUN rvm install ruby 3.2.0
...
 => ERROR [5/7] RUN usermod -a -G rvm $USER                                                             0.4s 
------                                                                                                       
 > [5/7] RUN usermod -a -G rvm $USER:                                                                        
#8 0.389 usermod: group 'rvm' does not exist                                                                 
...
 => ERROR [5/6] RUN source "/etc/profile.d/rvm.sh"                                                      0.8s
------                                                                                                       
 > [5/6] RUN source "/etc/profile.d/rvm.sh":
#8 0.453 /bin/sh: 1: source: not found
```

## Environment info

Ubuntu 22.04

**Comment by raelgc** [comment]
Sounds like a duplication of https://github.com/rvm/ubuntu_rvm/issues/8. If it's not the same issue, please, let me know and I'll re-open.

**Comment by matthiassb** [comment]
@raelgc can you reopen this please?

**Comment by raelgc** [comment]
@matthiassb Of course. But just to double check: are the solutions pointed in #8 not working? Is this a different issue?
