### ISSUE TITLE
Unable to install RVM ubuntu 22.04 (WSL)

### ISSUE THREAD

**Issue by pankaj-dahiya-sp** [rvm/ubuntu_rvm#77]
Apt update is failing after apt-add-repository

**Comment by pankaj-dahiya-sp** [comment]
In case you want full logs:


`Repository: 'deb https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu/ jammy main'
Description:
RVM (http://rvm.io) is a command-line tool which allows you to easily install, manage, and work with multiple ruby environments from interpreters to sets of gems.

Please, check install instructions here: https://github.com/rvm/ubuntu_rvm
More info: https://launchpad.net/~rael-gc/+archive/ubuntu/rvm
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/rael-gc-ubuntu-rvm-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/rael-gc-ubuntu-rvm-jammy.list
Adding key to /etc/apt/trusted.gpg.d/rael-gc-ubuntu-rvm.gpg with fingerprint 7BE3E5681146FD4F1A40EDA28094BB14F4E3FBBE
Ign:1 https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu jammy InRelease
Hit:2 https://download.docker.com/linux/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:1 https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu jammy InRelease
Ign:1 https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu jammy InRelease
Err:1 https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu jammy InRelease
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 185.125.190.52 443]
Reading package lists... Done
W: Failed to fetch https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu/dists/jammy/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 185.125.190.52 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
Ign:1 https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 https://download.docker.com/linux/ubuntu jammy InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:1 https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu jammy InRelease
Ign:1 https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu jammy InRelease
Err:1 https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu jammy InRelease
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 185.125.190.52 443]
Reading package lists... Done
W: Failed to fetch https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu/dists/jammy/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 185.125.190.52 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package rvm`

**Comment by cnebril2020** [comment]
Hi there! I was facing the same problem and i fixed using the command:
```\curl -sSL https://get.rvm.io | bash -s stable --ruby```
This command allows you to install RVM stable with ruby, in case you want to know more options in your installation check the RVM install guide [here](https://rvm.io/rvm/install#any-other-system). Maybe there is an issue with your operating system. Let me know if it worked for you!

**Comment by raelgc** [comment]
@pankaj-dahiya-sp Thanks for reporting this issue. Sounds like you're facing a missing certificate from Canonical PPAs. Are you trying this under a docker container? If yes, try [this solution](https://askubuntu.com/a/1145374/138621):

    sudo apt install ca-certificates

@cnebril2020 Yes, install `rvm` directly is always an option. The downside is that you'll miss automatic updates from `rvm`.
