### ISSUE TITLE
Fish(?) - missing end to balance this if statement

### ISSUE THREAD

**Issue by cyrus01337** [rvm/ubuntu_rvm#82]
## Description

Upon sourcing the RVM script via `source /etc/profile.d/rvm.sh` and piping through Bash (`source /etc/profile.d/rvm.sh | bash`), a Bash parsing error is received. This also causes RVM to incompletely install, and not show up as a command.

## Steps to reproduce

 1. Have a Ubuntu 23.04 machine with Fish 3.6.0 installed - this error was reproduced with Ubuntu Budgie specifically, though I would think a DE wouldn't affect installation
 2. Go through the setup
 3. Get stuck during installation because Bash script cannot be run

## Expected behavior

The source file to be run, and RVM to be found as a command.

## Actual behavior

* [source](https://gist.github.com/cyrus01337/dc3d1024b8ef97e29bded9dc60b48d0e)

## Environment info

```
───────┬──────────────────────────────────────────────────
       │ File: /etc/lsb-release
───────┼──────────────────────────────────────────────────
   1   │ DISTRIB_ID=Ubuntu
   2   │ DISTRIB_RELEASE=23.04
   3   │ DISTRIB_CODENAME=lunar
   4   │ DISTRIB_DESCRIPTION="Ubuntu 23.04"
───────┴──────────────────────────────────────────────────
```

**Comment by raelgc** [comment]
Hi @cyrus01337 and thanks for your time reporting this. Please, what is Fish?

**Comment by cyrus01337** [comment]
[Fish](https://github.com/fish-shell/fish-shell) is another shell like Zsh but not based on it, Bash is interpreted differently if I'm to run the Shell script using Fish, as shown above.

**Comment by cyrus01337** [comment]
I've moved away from Fish since I'm afraid, if anyone else wants to take this up they're more than welcome to do so.

**Comment by MarcBresson** [comment]
this is still happening in the latest version

**Comment by pkuczynski** [comment]
@MarcBresson PR is welcome!
