### ISSUE TITLE
 Unable to install rvm on Ubuntu 23.10 (mantic)

### ISSUE THREAD

**Issue by matt22207** [rvm/ubuntu_rvm#83]
## Description

rvm unavailable on Ubuntu 23.10 (mantic)

## Steps to reproduce

sudo apt-get install software-properties-common
sudo apt-add-repository -y ppa:rael-gc/rvm
sudo apt-get update
sudo apt-get install rvm

## Expected behavior

rvm should install

## Actual behavior

$ sudo apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu mantic InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu mantic-updates InRelease                                                                                           
Hit:5 http://us.archive.ubuntu.com/ubuntu mantic-backports InRelease                                                                                         
Hit:8 http://security.ubuntu.com/ubuntu mantic-security InRelease                                                                     
Ign:10 https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu mantic InRelease      
Err:12 https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu mantic Release
  **404  Not Found [IP: 185.125.190.52 443]**
Reading package lists... Done
**E: The repository 'https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu mantic Release' does not have a Release file.**

## Environment info

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.10
DISTRIB_CODENAME=mantic
DISTRIB_DESCRIPTION="Ubuntu 23.10"

**Comment by raelgc** [comment]
Thanks for reporting that @matt22207 and sorry for the inconvenience. Packages for `mantic` is now on place.

**Comment by matt22207** [comment]
thanks @raelgc .. much appreciated! keep up the good work
