### ISSUE TITLE
Unable to install rvm on Ubuntu 24.04 (noble)

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [rvm/ubuntu_rvm#84]
## Description

RVM fails to install on the new LTS Ubuntu 24.04 (noble)

## Steps to reproduce

```bash
sudo apt-get install software-properties-common
sudo apt-add-repository -y ppa:rael-gc/rvm
sudo apt-get update
sudo apt-get install rvm
```

## Expected behavior

RVM Installs

## Actual behavior

```bash
sudo apt update
Hit:1 http://mirrors.digitalocean.com/ubuntu noble InRelease
Hit:2 https://download.docker.com/linux/ubuntu noble InRelease
Hit:3 http://mirrors.digitalocean.com/ubuntu noble-updates InRelease
Hit:4 http://mirrors.digitalocean.com/ubuntu noble-backports InRelease
Hit:5 https://repos.insights.digitalocean.com/apt/do-agent main InRelease
Hit:6 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu noble InRelease
Ign:8 https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu noble InRelease
Err:9 https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu noble Release
  404  Not Found [IP: 2620:2d:4000:1::81 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/rael-gc/rvm/ubuntu noble Release' does not have a Release file.
```

## Environment info

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"
```

I'm assuming this is just another instance of #83 where they haven't been uploaded yet, but just wanted to bring it to your attention. Love how easy it is to install RVM on ubuntu, please keep up the great work 👍

**Comment by raelgc** [comment]
I'm building the package for 24.04 now. Sorry for my late. I totally forgot about it, ultra busy week.

**Comment by raelgc** [comment]
I've fired the build and it'll be available in few hours. Please keep checking the status in https://launchpad.net/~rael-gc/+archive/ubuntu/rvm/+packages. I need some sleep.

**Comment by BatedUrGonnaDie** [comment]
@raelgc reporting back than I'm now seeing success on `sudo apt update` and `sudo apt install rvm` is also successfully. Thanks a bunch!

**Comment by raelgc** [comment]
Thanks for the feedback @BatedUrGonnaDie! Sorry for the inconvenience.
